name: GitHub-Profile-3D-Contrib

on:
  # 毎日日本時間の午前9時に実行（UTCでは0時）
  schedule:
    - cron: "0 0 * * *"
  # pushがあった時にも手動で実行できるようにする
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3D-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user: ${{ github.repository_owner }}
          
    # 必要に応じてオプションを追加
    # with:
    #   github_token: ${{ secrets.GITHUB_TOKEN }}
    #   github_user: ${{ github.repository_owner }}
    #   # 色のテーマを変更する場合 (例: 'dark', 'solarized', 'radical' など)
    #   theme: 'dark'
    #   # Z軸のスケールを調整する場合
    #   z_scale: '1.4'
